In [1]:
import pandas as pd
import numpy as np

dataframe.drop() 
    원본 DataFrame을 변경하지 않고, 지정한 열이나 행을 삭제한 새 DataFrame 객체를 반환합니다.
    inplace=True 옵션설정시 원본 DataFrame 직접 수정

In [14]:
# DataFrame 생성
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'class': [7, 8, 9]}
df = pd.DataFrame(data)

# drop() 호출하면 새로운 dataframe이 생성된다.
new_df = df.drop(columns=['class'])

print("원본 DataFrame:")
print(df)  # 'class' 열이 그대로 있음

print("\n새로운 DataFrame:")
print(new_df)  # 'class' 열이 삭제된 새로운 DataFrame

원본 DataFrame:
   A  B  class
0  1  4      7
1  2  5      8
2  3  6      9

새로운 DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

dataframe.drop()

    용도 
        인덱스(행)나 컬럼(열)의 라벨(label)을 기준으로 지정된 행이나 열을 삭제할 때 사용합니다.
        라벨에 의한 명시적으로 데이터를 제거할때 사용합니다.

In [4]:
# 인덱스(행) 삭제
df.drop([0, 2], axis=0, inplace=True)

# 컬럼(열) 삭제
df.drop(['A', 'B'], axis=1, inplace=True)

불리언 인덱싱(Boolean Indexing)

  배열(NumPy)이나 데이터프레임(pandas)에서 “조건식이 True인 원소만 골라내는” 필터링 기법

    용도  
      조건에 따른 필터링에 의한 데이터를 제거할때 사용합니다. 
      특정 조건을 만족하는 행들을 선택하여 새로운 DataFrame으로 반환합니다.

In [16]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'class': [7, 8, 9]}
df = pd.DataFrame(data)
df

   A  B  class
0  1  4      7
1  2  5      8
2  3  6      9

In [18]:
df = df[df['class'] < 8] # 8 이상 row 삭제 = 8 보다 작은 row 만만
df

   A  B  class
0  1  4      7

In [24]:
# DataFrame 생성
data = {'A': [1, 2, 3], 'B': [4, 5, np.nan], 'class': [7, 8, 9]}
df = pd.DataFrame(data)
df

   A    B  class
0  1  4.0      7
1  2  5.0      8
2  3  NaN      9

In [25]:
df['A']

0    1
1    2
2    3
Name: A, dtype: int64

In [26]:
df[df['A'] == 1]

   A    B  class
0  1  4.0      7

In [27]:
df.isnull().sum()

A        0
B        1
class    0
dtype: int64

dataframe.dropna() 

    DataFrame에서 결측치(NA, NaN 등)가 포함된 행 또는 열을 제거하는 데 사용됩니다.  
    기본적으로 결측치가 하나라도 포함된 행을 삭제하지만, 옵션을 통해 열을 삭제하거나 특정 조건을 설정할 수 있습니다.

    axis
        axis=0 (기본값)은 결측치가 있는 행을 제거합니다.
        axis=1은 결측치가 있는 열을 제거합니다.
    how
        'any' (기본값)은 한 개라도 결측치가 있으면 삭제합니다.
        'all' 'all'은 모든 값이 결측치인 행(또는 열)만 삭제합니다.
    thresh
        지정된 axis에 대해서 결측치가 아닌 값의 최소 개수를 지정합니다.
    subset
        특정 열에 대해서만 결측치 여부를 확인하여 삭제할 수 있습니다.
    inplace
        inplace=True로 설정하면 원본 DataFrame을 직접 수정합니다.

In [29]:
df_na = df.dropna(axis=0, how='any')
df_na

   A    B  class
0  1  4.0      7
1  2  5.0      8

dataframe.loc()

In [16]:
df = pd.DataFrame(
    {'age':[25,30,22,40],'city':['Seoul','Gyeonggi','Gyeongsangbuk','Gwangju']},
    index=['ROH','KIM','CHO', 'LEE']
)
df

     age           city
ROH   25          Seoul
KIM   30       Gyeonggi
CHO   22  Gyeongsangbuk
LEE   40        Gwangju

In [17]:
# 1) 단일 라벨 행
df.loc['KIM']                  # Series 반환

age           30
city    Gyeonggi
Name: KIM, dtype: object

In [11]:
# 2) 여러 행 & 여러 열 선택
df.loc[['KIM','ROH'], ['age','city']]

     age      city
KIM   30  Gyeonggi
ROH   25     Seoul

In [13]:
# 3) 라벨 슬라이스 (포함 범위)
df.loc['KIM':'CHO', :]        # 세 행 모두

     age           city
KIM   30       Gyeonggi
CHO   22  Gyeongsangbuk

In [14]:
# 4) 불리언 마스크
df.loc[df['age'] > 24, 'city']

ROH       Seoul
KIM    Gyeonggi
LEE     Gwangju
Name: city, dtype: object

In [19]:
# 5) 값 수정
df.loc['ROH', 'city'] = 'Gwangju'

In [20]:
df

     age           city
ROH   25        Gwangju
KIM   30       Gyeonggi
CHO   22  Gyeongsangbuk
LEE   40        Gwangju