In [1]:
import pandas as pd

def get_df() :
    return pd.DataFrame({
        'A': [1, 2, 2, 3, 3],
        'B': [10, 20, 20, 30, 30],
        'C': ['x', 'y', 'y', 'z', 'z']
    })
    
print(get_df())
#    A   B  C
# 0  1  10  x
# 1  2  20  y
# 2  2  20  y
# 3  3  30  z
# 4  3  30  z

   A   B  C
0  1  10  x
1  2  20  y
2  2  20  y
3  3  30  z
4  3  30  z

In [2]:
# 1) 모든 컬럼 동일한 행 중복 제거 (첫 행만 남김)
df1 = get_df().drop_duplicates()
# 결과: index 0,1,3 만 남음
df1

   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z

In [3]:
# 2) 특정 컬럼만 보고 중복 제거
df2 = get_df().drop_duplicates(subset=['A'])
# A 값을 기준으로 중복 제거 → index 0,1,3 만 남음

df2

   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z

In [4]:
# 3) 마지막 행만 남기기
df3 = get_df().drop_duplicates(keep='last')
# 결과: index 0,2,4 만 남음
df3

   A   B  C
0  1  10  x
2  2  20  y
4  3  30  z

In [5]:
# 4) 원본 수정
get_df().drop_duplicates(inplace=True)
# df 자체가 중복 제거된 상태로 바뀜

In [6]:
# 5) 인덱스 재정렬
df_reset = get_df().drop_duplicates(ignore_index=True)
# 결과 인덱스가 0,1,2,...로 재배치