In [2]:
import pandas as pd

<h1> merge </h1>
데이터베이스 스타일의 Join(SQL JOIN) 연산을 수행하여 두 개의 DataFrame(혹은 이름이 지정된 Series)을 병합하는 함수

In [3]:
df_l = pd.DataFrame({
    'key': ['A','B','C'],
    'L':   [1,   2,   3]
})

df_r = pd.DataFrame({
    'key': ['B','C','D'],
    'R':   [4,   5,   6]
})

In [4]:
df_l

  key  L
0   A  1
1   B  2
2   C  3

In [6]:
df_r

  key  R
0   B  4
1   C  5
2   D  6

<h1> How = 'inner' </h1>

공통된 key를 기준으로 dataframe or series를 병합합니다다.

In [7]:
pd.merge(df_l, df_r, on='key', how='inner')

  key  L  R
0   B  2  4
1   C  3  5

<h1> How = 'left' </h1>

In [8]:
pd.merge(df_l, df_r, on='key', how='left')

  key  L    R
0   A  1  NaN
1   B  2  4.0
2   C  3  5.0

<h1> How = 'right' </h1>

In [9]:
pd.merge(df_l, df_r, on='key', how='right')

  key    L  R
0   B  2.0  4
1   C  3.0  5
2   D  NaN  6

<h1> How = 'outer' </h1>

In [10]:
pd.merge(df_l, df_r, on='key', how='outer')

  key    L    R
0   A  1.0  NaN
1   B  2.0  4.0
2   C  3.0  5.0
3   D  NaN  6.0