In [2]:
import pandas as pd

<h1> concat </h1>
concat 함수는 동일한 구조(컬럼)를 가진 로그나 시간별 데이터프레임을 이어 붙일때 사용합니다.

df1 과 df2 는 column A 와 B 를 가진 구조를 가지고 있습니다.

In [ ]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=[0, 1]) 
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]}, index=[2, 3])

In [5]:
df1

   A  B
0  1  3
1  2  4

In [6]:
df2

   A  B
2  5  7
3  6  8

In [12]:
df1_df2 = pd.concat([df1, df2])
df1_df2

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

다른 구조를 가진 dataframe을 concat 하면, 모든 컬럼의 합집합을 만들고, 없는 위치엔 NaN이 들어갑니다.

df3 는 column A 와 C 를 가진 구조로 [df1, df2] 와는 다른 구조를 가지고 있습니다.

In [11]:
df3 = pd.DataFrame({'A': [5, 6], 'C': [9, 10]}, index=[4, 5])
df3

   A   C
4  5   9
5  6  10

In [13]:
df1_df2_df3 = pd.concat([df1_df2, df3])
df1_df2_df3

   A    B     C
0  1  3.0   NaN
1  2  4.0   NaN
2  5  7.0   NaN
3  6  8.0   NaN
4  5  NaN   9.0
5  6  NaN  10.0

<h1> axis </h1>
axis = 0 은 row(행), axis = 1 은 column(열) 방향으로 dadaframe을 병합합니다.

In [17]:
df1_df2_axis_0 = pd.concat([df1, df2] , axis = 0)
df1_df2_axis_0

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [18]:
df1_df2_axis_1 = pd.concat([df1, df2] , axis = 1)
df1_df2_axis_1

     A    B    A    B
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
2  NaN  NaN  5.0  7.0
3  NaN  NaN  6.0  8.0

<h1> join </h1>
join 함수는 두 객체의 인덱스(또는 컬럼) 교집합(inner) 또는 합집합(outer, 기본)

In [20]:
df1_df3_inner = pd.concat([df1, df3], join='inner')
df1_df3_inner

   A
0  1
1  2
4  5
5  6

In [21]:
df1_df3_outer = pd.concat([df1, df3], join='outer')
df1_df3_outer

   A    B     C
0  1  3.0   NaN
1  2  4.0   NaN
4  5  NaN   9.0
5  6  NaN  10.0

<h1> ignore_index </h1>
True 로 설정하면 새로 0부터 순차적 인덱스 부여

In [23]:
df1_df2_ignore_inex_true = pd.concat([df1, df2], axis=0 , ignore_index=True)
df1_df2_ignore_inex_true

   A    B     C
0  1  3.0   NaN
1  2  4.0   NaN
2  5  NaN   9.0
3  6  NaN  10.0

<h1> keys </h1>

dafaframe 별로 레이블을 부여합니다.

In [25]:
df1

   A  B
0  1  3
1  2  4

In [32]:
df2

   A  B
2  5  7
3  6  8

In [24]:
df1_df2_keys = pd.concat([df1, df2], keys=['first', 'second'])
df1_df2_keys

          A  B
first  0  1  3
       1  2  4
second 2  5  7
       3  6  8

<h1> levels & names </h1>
keys 로 만든 multi index의 levels 와 names 지정

In [48]:
keys = [('group1', 'one') , ('group1', 'two')]
levels = [['group1', 'group2'], ['one', 'two']]
names = ['Group', 'Subgroup']

level_names = pd.concat([df1, df2]
                        , keys = keys
                        , levels = levels
                        , names = names)
level_names

                   A  B
Group  Subgroup
group1 one      0  1  3
                1  2  4
       two      2  5  7
                3  6  8

<h1> verify_integrity </h1>
index  중복이 있으면 예외를 발생시켜 데이터 중복 확인

In [35]:
df6 = pd.DataFrame({'A':[9,10],'B':[11,12]}, index=[1,2])
df6

    A   B
1   9  11
2  10  12

In [36]:
df1

   A  B
0  1  3
1  2  4

In [38]:
pd.concat([df1, df6])

    A   B
0   1   3
1   2   4
1   9  11
2  10  12

In [37]:
pd.concat([df1, df6], verify_integrity=True)

ValueError: Indexes have overlapping values: Index([1], dtype='int64')

<h1> sort </h1>
axis=0 병합 시 컬럼 순서를 정렬할지 여부 (False 기본)

In [104]:
df7 = pd.DataFrame({'C':[1,2]}, index=[0,1])
df7

   C
0  1
1  2

In [105]:
df8 = pd.DataFrame({'B':[5,6], 'A':[7,8]}, index=[0,1])
df8

   B  A
0  5  7
1  6  8

In [130]:
pd.concat([df8, df7], axis=0, sort=False)

     B    A    C
0  5.0  7.0  NaN
1  6.0  8.0  NaN
0  NaN  NaN  1.0
1  NaN  NaN  2.0

In [131]:
pd.concat([df8, df7], axis=0, sort=True)

     A    B    C
0  7.0  5.0  NaN
1  8.0  6.0  NaN
0  NaN  NaN  1.0
1  NaN  NaN  2.0